language: node_js
node_js:
 - "stable"

script: 
 - npm install
 - npm test
 - npm run build

 deploy: 
  provider: surge
  skip_cleaner : true
  domain: react-test-case-ghazanfar-ali.surge.sh
  project: ./build/

  on:
  branch: main